name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push - Slack Scroll
      id: docker_build
      uses: docker/build-push-action@v5
      with:
        context: ./slack_scroll
        push: true
        tags: tazard/slack-scroll:latest
        platforms: linux/arm/v6

    - name: Build and push - Web Interface
      id: docker_build_web_interface
      uses: docker/build-push-action@v5
      with:
        context: ./web_interface
        push: true
        tags: tazard/slack-scroll-web-interface:latest
        platforms: linux/arm/v6
  